os: linux
language: ruby
rvm:
- 2.6.3

install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source

notifications:
  irc: "ircs://chat.freenode.net:7070/#sfzformat-dev"
