defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/css/style.css
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - new_post.pl
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - setup.sh
  - TODO.md
  - yarn.lock
  - yarn-error.log

plugins:
  - jekyll-sitemap

url: "https://sfzformat.github.io"

spdx_license_id: "MPL-2.0"

locale:
  default: "en"

organization:
  name: "SFZ Format"
  url: "https://sfzformat.github.io"

authors:
  content: "Karoryfer Samples and SFZ Format Team"
  web: "RedTide and SFZ Format Team"

google:
  analytics_code: UA-138937603-1
  cse_code:

disqus_shortname:
