defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - new_post
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - setup
  - site.conf
  - TODO.md
  - yarn.lock
  - assets/css/style.css
  - assets/css/style.css.map
  - assets/css/style.min.css.map
  - assets/js/scripts.min.js.map

url: "https://sfzformat.github.io"

plugins:
  - jekyll-sitemap

organization_name: SFZ Format
# disqus_shortname: 
