defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - new_post
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - setup.sh
  - TODO.md
  - yarn.lock
  - yarn-error.log
  - assets/css/style.css

plugins:
  - jekyll-sitemap

organization_name: SFZ Format

url: "https://sfzformat.github.io"
