# Default front-matter variables: global, pages and posts
defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- assets/css/style.css
- Gemfile
- Gemfile.lock
- LICENSE
- new_post.pl
- new_post.sh
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

url: "https://sfzformat.github.io"

organization:
  name: "SFZ Format"
  url: "https://sfzformat.github.io"

repository:
  branch: "source"
  url: "https://github.com/sfzformat/sfzformat.github.io"

locale:
  default: "en"

authors:
  content: "Karoryfer Samples and SFZ Format Team"
  web: "RedTide and SFZ Format Team"

google:
  analytics_code: UA-138937603-1
  cse_code:

spdx_license_id:
disqus_shortname:
